### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by michael1006** [notjosh/Outside#1]
Hi, I _love_ the idea of WindowSwap as a screensaver so I'm really excited to try this out.

Unfortunately, when I install it (0.1.0) on my M1 Air Monterey, it's just a black screen with a loading indicator in the bottom-right hand corner. It's been that way for about 10 minutes.

Do you know if this works under Monterey? I have no idea what aspect of it is failing to load/display, so please let me know if there's anything I can do to send you logs or anything to help debug.

**Comment by notjosh** [comment]
Hey! I actually just noticed this issue on my MacBook earlier - I believe it was working until yesterday or so. I'm guessing some of the URLs to the videos changed, so it can't load any.

It's been working under Monterey since beta 1.

I'll poke around over the weekend (because I use the screensaver also!), and let you know what I find.

**Comment by notjosh** [comment]
I've just released 0.2.0 ([link](https://github.com/notjosh/Outside/releases/tag/v0.2.0)), if you want to give that a shot? Seems to have fixed it for me on multiple machines. It's _possible_ it'll load the previous/cached data on first run, but hopefully from at least the second run works okay.

Let me know how you get on! If you're still having issues, re-open and we'll figure it out :)

**Comment by michael1006** [comment]
Works like a charm, thanks! I love it.

Just so you're aware, for me the "mini" version that shows inside the System Preferences window is still black with an eternal loading spinner. But when you click "Preview" it works in full-screen. So doesn't bother me at all.
